pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["administration.htm","Advanced Features &#62; Server Lua API &#62; Administrator","Administrator",""],
["administrator_console.htm","Quick Start &#62; Administration Console","Administration Console",""],
["admin_log.htm","Administration &#62; Admin Log","Admin Log",""],
["admin_log_setting.htm","Administration &#62; Settings &#62; General Settings","General Settings",""],
["admin_setting_ip_access.htm","Administration &#62; Settings &#62; IP Access","IP Access",""],
["admin_setting_listener.htm","Administration &#62; Settings &#62; Listener","Listener",""],
["admin_user.htm","Administration &#62; Admin User","Admin User",""],
["aoe.htm","Quick Start &#62; Quick Start Guide","Quick Start Guide",""],
["audit__report.htm","Domain &#62; Logs &#38; Status &#62; Audit &#38; Report","Audit &#38; Report",""],
["compression.htm","Domain &#62; Domain Settings &#62; General Settings &#62; Password &#38; Security","Password &#38; Security",""],
["connection_limit.htm","Domain &#62; Domain Settings &#62; General Settings &#62; Connection Limit","Connection Limit",""],
["custom_log.htm","Server &#62; Settings &#62; General Settings &#62; Customized Logo","Customized Logo",""],
["database.htm","Advanced Features &#62; Database Schema","Database Schema",""],
["database_example.htm","Advanced Features &#62; Database Example","Database Example",""],
["data_storage.htm","Domain &#62; Domain Settings &#62; Authentication Settings","Authentication Settings",""],
["domain_activity.htm","Domain &#62; Logs &#38; Status &#62; Activity","Activity",""],
["domain_event_manager.htm","Domain &#62; Event Manager","Event Manager",""],
["domain_function.htm","Advanced Features &#62; Server Lua API &#62; Domain Function","Domain Function",""],
["domain_log.htm","Domain &#62; Logs &#38; Status &#62; Domain Log","Domain Log",""],
["domain_log_setting.htm","Domain &#62; Domain Settings &#62; General Settings &#62; Domain Log","Domain Log",""],
["domain_setting_miscellaneous.htm","Domain &#62; Domain Settings &#62; General Settings &#62; Miscellaneous","Miscellaneous",""],
["domain_status.htm","Domain &#62; Logs &#38; Status &#62; Domain Status","Domain Status",""],
["edtions.htm","Wing FTP Server &#62; Editions","Editions",""],
["email_notification.htm","Quick Start &#62; Email Notification","Email Notification",""],
["file_access.htm","Domain &#62; Domain Settings &#62; File Access","File Access",""],
["file_access2.htm","Server &#62; Settings &#62; General Settings &#62; File Access","File Access",""],
["ftp_messages.htm","Domain &#62; Domain Settings &#62; FTP Messages","FTP Messages",""],
["ftp_pasv_mode.htm","Domain &#62; Domain Settings &#62; General Settings &#62; FTP Passive Mode","FTP Passive Mode",""],
["gateway_manager.htm","Server &#62; Settings &#62; Gateway Manager","Gateway Manager",""],
["get_set_options.htm","Advanced Features &#62; Server Lua API &#62; Get/Set Options","Get/Set Options",""],
["global_function.htm","Advanced Features &#62; Server Lua API &#62; System Function","System Function",""],
["graphs_chart.htm","Domain &#62; Logs &#38; Status &#62; Graphs","Graphs",""],
["group_general.htm","Domain &#62; Groups &#62; Group Setting","Group Setting",""],
["ip_access.htm","Domain &#62; Domain Settings &#62; IP Access","IP Access",""],
["ip_access2.htm","Server &#62; Settings &#62; General Settings &#62; IP Access","IP Access",""],
["ip_whitelisting.htm","Domain &#62; Domain Settings &#62; IP Whitelisting","IP Whitelisting",""],
["listners.htm","Domain &#62; Domain Settings &#62; Listeners","Listeners",""],
["lua_language.htm","Advanced Features &#62; Lua Language","Lua Language ",""],
["miscellaneous.htm","Server &#62; Settings &#62; General Settings &#62; Miscellaneous","Miscellaneous",""],
["miscellaneous2.htm","Advanced Features &#62; Server Lua API &#62; Miscellaneous","Miscellaneous",""],
["purchase.htm","Wing FTP Server &#62; Purchase","Purchase",""],
["ratio__quota.htm","Domain &#62; Users &#62; User &#62; Ratio &#38; Quota","User &#62; Ratio &#38; Quota",""],
["requirements.htm","Wing FTP Server &#62; Requirements","Requirements",""],
["router__firewall.htm","Quick Start &#62; Router &#38; Firewall","Router and Firewall",""],
["security.htm","Server &#62; Settings &#62; General Settings &#62; Security","Security",""],
["server_lua_api.htm","Advanced Features &#62; Server Lua API","Server Lua API",""],
["server_variables.htm","Advanced Features &#62; Server Variables","Server Variables",""],
["sfv_directory.htm","Domain &#62; Domain Settings &#62; SFV Directory","SFV Directory",""],
["smtp_config_manager.htm","Server &#62; Settings &#62; SMTP Server Manager","SMTP Server Manager",""],
["speed_limit.htm","Domain &#62; Domain Settings &#62; General Settings &#62; Data Transfer Limit","Data Transfer Limit",""],
["ssh_key_manager.htm","Server &#62; Settings &#62; SSH Host Key Manager","SSH Host Key Manager",""],
["ssl_certificate_manager.htm","Server &#62; Settings &#62; SSL Certificate Manager","SSL Certificate Manager",""],
["system_log.htm","Server &#62; Logs &#38; Status &#62; Server Log","Server Log",""],
["system_log_setting.htm","Server &#62; Settings &#62; General Settings &#62; Logs","Logs",""],
["system_status.htm","Server &#62; Logs &#38; Status &#62; Server Status","Server Status",""],
["system_task.htm","Server &#62; Task Scheduler","Task Scheduler",""],
["temp_ban.htm","Domain &#62; Logs &#38; Status &#62; Temp Ban","Temp Ban",""],
["transfer_limit.htm","Domain &#62; Domain Settings &#62; Transfer Quota Limit","Transfer Quota Limit",""],
["uoeoeia.htm","Wing FTP Server &#62; Overview","Overview",""],
["user_access_time.htm","Domain &#62; Users &#62; User &#62; Access Time","User &#62; Access Time",""],
["user_directory.htm","Domain &#62; Users &#62; User &#62; Directory","User &#62; Directory",""],
["user_file_access.htm","Domain &#62; Users &#62; User &#62; File Access","User &#62; File Access",""],
["user_general.htm","Domain &#62; Users &#62; User &#62; General","User &#62; General",""],
["user_group.htm","Domain &#62; Users &#62; User &#62; Group","User &#62; Group",""],
["user_ip_access.htm","Domain &#62; Users &#62; User &#62; IP Access","User &#62; IP Access",""],
["user_limit.htm","Domain &#62; Users &#62; User &#62; Limit","User &#62; Limit",""],
["user_subfolder.htm","Domain &#62; Users &#62; User &#62; Subfolder","User &#62; Subfolder",""],
["user__group.htm","Advanced Features &#62; Server Lua API &#62; User &#38; Group","User and Group",""]];
